### ISSUE TITLE
Restore BSD support

### ISSUE THREAD

**Issue by drk1wi** [drk1wi/portspoof#11]
The relevant code is there... it's just a matter of time to sort some compilation issues.

**Comment by JustDevZero** [comment]
Something similar happens here... :(

Running FreeBSD:

ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
 new conn - thread choosen: 9 -  nr. of connections already in queue: 0
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
ERROR on accept: Software caused connection abort
Getsockopt failed: Protocol not available
