### ISSUE TITLE
ARM compatibility

### ISSUE THREAD

**Issue by h264** [drk1wi/portspoof#17]
As far as I know, Portspoof does not run on ARM devices at the moment.

Would it be possible to create a version of portspoof that runs on ARM, too?

**Comment by drk1wi** [comment]
I think that as long the OS will be Linux, then this shouldn't be a problem. What do you want to do?

**Comment by h264** [comment]
I am running a linux-based router (OS: IPFire) on an ARM-board. To confuse attackers, I want to include portspoof so it is active on the network interface which is connected to the internet.
On i686-systems, this is already working, but not on ARM-boards.
The architecture of my system is armv7l (Wandboard Quad, see http://wandboard.org/ for details).

Note: There is a discussion about this on the IPFire Forum, but it is in German only: http://forum.ipfire.org/viewtopic.php?f=17&t=12399&p=85407

**Comment by drk1wi** [comment]
Did you try to compile the source code on the ARM box itself? The compiler (g++) should then produce a binary in the right,  armv7l supported, format.

**Comment by h264** [comment]
Thanks for the hint, it worked fine. Portspoof is now running on ARM.
