### ISSUE TITLE
Portspoof crashes when using -f option

### ISSUE THREAD

**Issue by h264** [drk1wi/portspoof#19]
My portspoof installation (running on an ARM device) is working well by using the service emulation mode ("portspoof -c /path/to/portspoof.conf -s /path/to/portspoof_signatures -D").

However, when using any fuzzing mode but the -1 one, for example:
"portspoof -f /path/to/fuzzingfile.txt -D",
Portspoof crashes instantly.

Maybe this is because a wrong syntax of the fuzzingfile.txt (some non-alphanumberic chars), but I don't know for sure.

**Comment by drk1wi** [comment]
Hi,
This feature will be rewritten in the upcoming release. 
Could you send me a coredump for the latest app with debug symbols compiled in ?
./configure CFLAGS="-ggdb3 -O0" CXXFLAGS="-ggdb3 -O0" LDFLAGS="-ggdb3"
then 'make' and before running portspoof enable dumps with this command ulimit -c unlimited.
