### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by amitgupta46** [drk1wi/portspoof#21]
Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-am
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/etc"'    -g -O2 -MT portspoof-connection.o -MD -MP -MF .deps/portspoof-connection.Tpo -c -o portspoof-connection.o `test -f 'connection.cpp' || echo './'`connection.cpp
connection.cpp:148:48: error: use of undeclared identifier 'SOL_IP'
  ...if ( getsockopt (threads[tid].clients[i], SOL_IP, SO_ORIGINAL_DST, (struct sockaddr_)...
                                               ^
connection.cpp:198:48: error: use of undeclared identifier 'SOL_IP'
  ...if ( getsockopt (threads[tid].clients[i], SOL_IP, SO_ORIGINAL_DST, (struct sockaddr_)...
                                               ^
connection.cpp:234:47: error: use of undeclared identifier 'SOL_IP'
                                if ( getsockopt (threads[tid].clients[i], SOL_IP, SO_...
                                                                          ^
3 errors generated.
make[2]: **\* [portspoof-connection.o] Error 1
make[1]: **\* [all] Error 2
make: **\* [all-recursive] Error 1

**Comment by drk1wi** [comment]
Hey amitgupta46,

On which OS are you trying to compile portspoof ? Right now only Linux is supported.
