### ISSUE TITLE
Run as Service Error

### ISSUE THREAD

**Issue by zegufe2015** [drk1wi/portspoof#24]
Hello,

I have installed Portspoof on Redhat 7.  
Finally I configured below command.
portspoof -c /usr/local/etc/portspoof.conf -s /usr/local/etc/portspoof_signatures -D

But when I restart computer Portspoof not working. 
What can I do?

Best regards.

**Comment by nailyk-fr** [comment]
This command means portspoof will run in background. 
To make it a service you need to write an [init](https://github.com/drk1wi/portspoof/blob/master/DOCS#L31-L33) script.
