### ISSUE TITLE
It doesn't work on Raspberry PI B

### ISSUE THREAD

**Issue by Marmeus** [drk1wi/portspoof#28]
I have been following INSTALL instructions but i did an nmap scan to my raspberry and it didn't work.

I look forward to hearing from you.

**Comment by jwgn** [comment]
It works perfectly fine on any Raspberry Pi. Check if your iptables rules are properly set.

**Comment by Marmeus** [comment]
I think there woudn't be any problem.

![iptables](https://user-images.githubusercontent.com/28514875/41506710-456b1c9a-7223-11e8-9bb5-2123eb9bd844.PNG)

**Comment by jwgn** [comment]
You need to setup REDIRECT rules. Read the documentation.

**Comment by drk1wi** [comment]
Hi,

Yes, you will need to configure iptables with a right set of redirect rules. Please check the repo, there are some examples of iptables config there.

Best Piotr
