### ISSUE TITLE
Documentation Link Bad On Home Page

### ISSUE THREAD

**Issue by war59312** [drk1wi/portspoof#31]
Hi,

The documentation link is bad on the home page.

"Check out the documentation page for further details."

Bad Link, points to docs. Should just be doc, as in:

Current:

https://github.com/drk1wi/portspoof/blob/master/DOCS

Correct:

https://github.com/drk1wi/portspoof/blob/master/DOC

Thanks,

Will

**Comment by drk1wi** [comment]
Hi Will,

Thank you for pointing this out. I have made the necessary corrections.

Best 
Piotr

**Comment by war59312** [comment]
I'm still getting the bad link here.
