### ISSUE TITLE
Fails to build with musl-libc - "connection.h: fatal error: sys/sysctl.h: No such file or directory"

### ISSUE THREAD

**Issue by mjeveritt** [drk1wi/portspoof#33]
Musl libc doesn't provide a separate sys/sysctl.h. Use linux/sysctl.h directly instead.

See https://bugs.gentoo.org/show_bug.cgi?id=717134 .

**Comment by R3try0** [comment]
Well for me at least, i just coped the sysctl.h from /usr/include/linux/sysctl.h and pasted to  /usr/include/x86_64-linux-gnu/sys/ and worked try that.

**Comment by tailordresden** [comment]
Yup, this happened to me too, latest version of arch. Copying /usr/include/linux/sysctl.h to /usr/include/sys/sysctl.h is what worked since I don't have a x86_64-linux-gnu folder. I read a comment somewhere suggesting sysctl was deprecated and was removed from glibc-2.32. Thanks for the suggestion.

**Comment by drk1wi** [comment]
fixed
