### ISSUE TITLE
Can't install portspoof 

### ISSUE THREAD

**Issue by victorseverin55** [drk1wi/portspoof#38]
Hello i tried so many times to find how to install but every time the error is when i put the comand make the error is:
Making all in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make  all-am
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Configuration.o -MD -MP -MF .deps/portspoof-Configuration.Tpo -c -o portspoof-Configuration.o `test -f 'Configuration.cpp' || echo './'`Configuration.cpp
In file included from Configuration.h:91,
                 from Configuration.cpp:38:
connection.h:48:10: fatal error: sys/sysctl.h: File o directory non esistente
   48 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:310: portspoof-Configuration.o] Errore 1
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: *** [Makefile:189: all] Errore 2
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
make: *** [Makefile:248: all-recursive] Errore 1

if anyone can help me i will be very happy thank you

**Comment by drk1wi** [comment]
fixed

**Comment by victorseverin55** [comment]
Hello sorry if i text again but he gives me an error when i text sudo make install:
Making install in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
test -z "/usr/local/bin" || /usr/bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c portspoof '/usr/local/bin'
/usr/bin/install: impossibile sovrascrivere la directory '/usr/local/bin/portspoof' con una non-directory
make[2]: *** [Makefile:243: install-binPROGRAMS] Errore 1
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: *** [Makefile:502: install-am] Errore 2
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
make: *** [Makefile:248: install-recursive] Errore 1

sorry for desturbing you time thanks.
