### ISSUE TITLE
Error to install portspoof

### ISSUE THREAD

**Issue by victorseverin55** [drk1wi/portspoof#40]
Hello sorry if i text again but he gives me an error when i text sudo make install:
Making install in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
test -z "/usr/local/bin" || /usr/bin/mkdir -p "/usr/local/bin"
/usr/bin/install -c portspoof '/usr/local/bin'
/usr/bin/install: impossibile sovrascrivere la directory '/usr/local/bin/portspoof' con una non-directory
make[2]: *** [Makefile:243: install-binPROGRAMS] Errore 1
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: *** [Makefile:502: install-am] Errore 2
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
make: *** [Makefile:248: install-recursive] Errore 1

sorry for desturbing you time thanks.

**Comment by victorseverin55** [comment]
sorry again and when i do make i dont know if this is an error at server when i so make:

Making all in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make  all-am
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
Making all in tools
make[1]: ingresso nella directory «/home/ghost/portspoof/tools»
make[1]: Nessuna operazione da eseguire per «all».
make[1]: uscita dalla directory «/home/ghost/portspoof/tools»
make[1]: ingresso nella directory «/home/ghost/portspoof»
make[1]: Nessuna operazione da eseguire per «all-am».
make[1]: uscita dalla directory «/home/ghost/portspoof»
                                                                                                                                  
┌──(ghost㉿ghost)-[~/portspoof]
└─$ sudo make check  
Making check in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
Making check in tools
make[1]: ingresso nella directory «/home/ghost/portspoof/tools»
make[1]: Nessuna operazione da eseguire per «check».
make[1]: uscita dalla directory «/home/ghost/portspoof/tools»
make[1]: ingresso nella directory «/home/ghost/portspoof»
make[1]: Nessuna operazione da eseguire per «check-am».
make[1]: uscita dalla directory «/home/ghost/portspoof»
                                                                                                                                  
┌──(ghost㉿ghost)-[~/portspoof]
└─$ cd             
                                                                                                                                  
┌──(ghost㉿ghost)-[~]
└─$ ls
Cam-Hackers  Immagini  Musica    request.txt  Scaricati  slowloris  wifi-pin
Documenti    Modelli   Pubblici  RTSPbrute    Scrivania  Video
                                                                                                                                  
┌──(ghost㉿ghost)-[~]
└─$ git clone https://github.com/drk1wi/portspoof.git
Clone in 'portspoof' in corso...
remote: Enumerating objects: 878, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 878 (delta 2), reused 2 (delta 1), pack-reused 865
Ricezione degli oggetti: 100% (878/878), 3.30 MiB | 4.27 MiB/s, fatto.
Risoluzione dei delta: 100% (474/474), fatto.
                                                                                                                                  
┌──(ghost㉿ghost)-[~]
└─$ ls
Cam-Hackers  Immagini  Musica     Pubblici     RTSPbrute  Scrivania  Video
Documenti    Modelli   portspoof  request.txt  Scaricati  slowloris  wifi-pin
                                                                                                                                  
┌──(ghost㉿ghost)-[~]
└─$ portspoof      
                                                                                                                                  
┌──(ghost㉿ghost)-[~/portspoof]
└─$ ls
aclocal.m4  auto       configure     COPYING        CREDITS  docs  INSTALL      Makefile.in  README     src           tools
AUTHORS     ChangeLog  configure.in  COPYRIGHT.GPL  DOC      FAQ   Makefile.am  NEWS         README.md  system_files
                                                                                                                                  
┌──(ghost㉿ghost)-[~/portspoof]
└─$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for inet_ntoa... yes
checking for memset... yes
checking for socket... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tools/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands
                                                                                                                                  
┌──(ghost㉿ghost)-[~/portspoof]
└─$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/ghost/portspoof/auto/missing --run aclocal-1.11 
/home/ghost/portspoof/auto/missing: riga 52: aclocal-1.11: comando non trovato
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.in'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
 cd . && /bin/bash /home/ghost/portspoof/auto/missing --run automake-1.11 --gnu
/home/ghost/portspoof/auto/missing: riga 52: automake-1.11: comando non trovato
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.in'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/ghost/portspoof/auto/missing --run autoconf
/home/ghost/portspoof/auto/missing: riga 52: autoconf: comando non trovato
WARNING: `autoconf' is missing on your system.  You should only need it if
         you modified `configure.in'.  You might want to install the
         `Autoconf' and `GNU m4' packages.  Grab them from any GNU
         archive site.
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for inet_ntoa... yes
checking for memset... yes
checking for socket... yes
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tools/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
Making all in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /home/ghost/portspoof/auto/missing --run autoheader)
/home/ghost/portspoof/auto/missing: riga 52: autoheader: comando non trovato
WARNING: `autoheader' is missing on your system.  You should only need it if
         you modified `acconfig.h' or `configure.in'.  You might want
         to install the `Autoconf' and `GNU m4' packages.  Grab them
         from any GNU archive site.
touch: impossibile fare touch di '[src/config.h].in': File o directory non esistente
rm -f stamp-h1
touch config.h.in
cd .. && /bin/bash ./config.status src/config.h
config.status: creating src/config.h
config.status: src/config.h is unchanged
make  all-am
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Configuration.o -MD -MP -MF .deps/portspoof-Configuration.Tpo -c -o portspoof-Configuration.o `test -f 'Configuration.cpp' || echo './'`Configuration.cpp
mv -f .deps/portspoof-Configuration.Tpo .deps/portspoof-Configuration.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-connection.o -MD -MP -MF .deps/portspoof-connection.Tpo -c -o portspoof-connection.o `test -f 'connection.cpp' || echo './'`connection.cpp
mv -f .deps/portspoof-connection.Tpo .deps/portspoof-connection.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Fuzzer.o -MD -MP -MF .deps/portspoof-Fuzzer.Tpo -c -o portspoof-Fuzzer.o `test -f 'Fuzzer.cpp' || echo './'`Fuzzer.cpp
mv -f .deps/portspoof-Fuzzer.Tpo .deps/portspoof-Fuzzer.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Portspoof.o -MD -MP -MF .deps/portspoof-Portspoof.Tpo -c -o portspoof-Portspoof.o `test -f 'Portspoof.cpp' || echo './'`Portspoof.cpp
mv -f .deps/portspoof-Portspoof.Tpo .deps/portspoof-Portspoof.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Server.o -MD -MP -MF .deps/portspoof-Server.Tpo -c -o portspoof-Server.o `test -f 'Server.cpp' || echo './'`Server.cpp
Server.cpp: In constructor ‘Server::Server(Configuration*)’:
Server.cpp:51:76: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   51 |                 pthread_create(&threads[i].tid, NULL, &process_connection, (void *) i);
      |                                                                            ^~~~~~~~~~
mv -f .deps/portspoof-Server.Tpo .deps/portspoof-Server.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Revregex.o -MD -MP -MF .deps/portspoof-Revregex.Tpo -c -o portspoof-Revregex.o `test -f 'Revregex.cpp' || echo './'`Revregex.cpp
mv -f .deps/portspoof-Revregex.Tpo .deps/portspoof-Revregex.Po
g++ -DHAVE_CONFIG_H -I.  -DCONFDIR='"/usr/local/etc"'    -g -O2 -MT portspoof-Utils.o -MD -MP -MF .deps/portspoof-Utils.Tpo -c -o portspoof-Utils.o `test -f 'Utils.cpp' || echo './'`Utils.cpp
mv -f .deps/portspoof-Utils.Tpo .deps/portspoof-Utils.Po
g++  -g -O2 -pthread  -o portspoof  portspoof-Configuration.o portspoof-connection.o portspoof-Fuzzer.o portspoof-Portspoof.o portspoof-Server.o portspoof-Revregex.o portspoof-Utils.o  
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
Making all in tools
make[1]: ingresso nella directory «/home/ghost/portspoof/tools»
make[1]: Nessuna operazione da eseguire per «all».
make[1]: uscita dalla directory «/home/ghost/portspoof/tools»
make[1]: ingresso nella directory «/home/ghost/portspoof»
make[1]: Nessuna operazione da eseguire per «all-am».
make[1]: uscita dalla directory «/home/ghost/portspoof»

thank you for your time

**Comment by drk1wi** [comment]
have you tried :

./configure
make
sudo make install ?

**Comment by scriptzteam** [comment]
The missing pieces from the error are:

    aclocal
    automake
    autoconf

install them maybe?

**Comment by victorseverin55** [comment]
I tried all this ./configure, make and sudo make install.
I installed automake, autoconf but aclocal was installed.
when i do make:
└─$ sudo make               
Making all in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make  all-am
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
Making all in tools
make[1]: ingresso nella directory «/home/ghost/portspoof/tools»
make[1]: Nessuna operazione da eseguire per «all».
make[1]: uscita dalla directory «/home/ghost/portspoof/tools»
make[1]: ingresso nella directory «/home/ghost/portspoof»
make[1]: Nessuna operazione da eseguire per «all-am».
make[1]: uscita dalla directory «/home/ghost/portspoof»

when i do sudo make install:
└─$ sudo make install
Making install in src
make[1]: ingresso nella directory «/home/ghost/portspoof/src»
make[2]: ingresso nella directory «/home/ghost/portspoof/src»
test -z "/usr/local/bin" || /usr/bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c portspoof '/usr/local/bin'
/usr/bin/install: impossibile sovrascrivere la directory '/usr/local/bin/portspoof' con una non-directory
make[2]: *** [Makefile:243: install-binPROGRAMS] Errore 1
make[2]: uscita dalla directory «/home/ghost/portspoof/src»
make[1]: *** [Makefile:502: install-am] Errore 2
make[1]: uscita dalla directory «/home/ghost/portspoof/src»
make: *** [Makefile:248: install-recursive] Errore 1

**Comment by drk1wi** [comment]
do you have the target dir? /usr/local/bin

**Comment by victorseverin55** [comment]
└─$ ls -la /usr/local/bin
totale 12
drwxr-xr-x  3 root  root  4096 19 ago 01.35 .
drwxr-xr-x 11 root  root  4096  9 ago 23.17 ..
drwxr-xr-x  7 ghost ghost 4096 19 ago 02.06 portspoof
