### ISSUE TITLE
Support for docker

### ISSUE THREAD

**Issue by Robin-Sch** [drk1wi/portspoof#46]
Would it be possible to run portspoof inside of docker? If not, maybe you should remove this (empty?) package https://hub.docker.com/r/drk1wi/portspoof_docker .

Only downside would be is that you have to specify port ranges to expose all ports....

**Comment by drk1wi** [comment]
it is possible, but I will remove it.
>Only downside would be is that you have to specify port ranges to expose all ports....
only one would have to be exposed.
