### ISSUE TITLE
FYI nftables solution

### ISSUE THREAD

**Issue by jgowdy** [drk1wi/portspoof#52]
# Port scanning mitigation chain for synproxy
        chain SYNPROXY {
		# Primary defense is synproxy which will send a stateless SYN+ACK
                synproxy mss 1460 wscale 7 sack-perm timestamp;
		# Fallback is manually sending a stateless SYN+ACK, then drop the SYN
                tcp flags syn,ack counter drop comment "send stateless SYN+ACK, then drop the SYN";
        }

Doesn't do the protocol signatures, but still hamstrings port scans

**Comment by drk1wi** [comment]
thanks, but this is easy to bypass.
